# Generated by Django 3.0.6 on 2020-05-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=200, unique=True)),
                ('ten_lop', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sinhvien',
            options={'verbose_name': 'Sinh viên', 'verbose_name_plural': 'Sinh viên'},
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ma_sv',
            field=models.CharField(max_length=200, unique=True, verbose_name=' Mã Sinh Viên'),
        ),
        migrations.CreateModel(
            name='SinhVienLopHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.LopHoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SinhVien')),
            ],
        ),
    ]
